"use client";

import Link from "next/link";
import { useTheme, THEME_CONFIGS } from "@/components/ThemeProvider";
import { useUserStore, type WorkoutTheme } from "@/store/userStore";

const FEATURES = [
  { icon: "⚔️", title: "Anime Training Systems", desc: "Choose from Saiyan, Shinobi, Hunter, or Sorcerer paths with scientifically backed workouts." },
  { icon: "🤖", title: "AI Nutrition Coach", desc: "Personalized meal plans generated by AI based on your body metrics and goals." },
  { icon: "📈", title: "Progress Tracking", desc: "Track streaks, calories burned, exercises completed, and weekly progress charts." },
  { icon: "🎮", title: "RPG Leveling System", desc: "Earn XP with every workout. Level up from Beginner to Elite Warrior." },
  { icon: "💧", title: "Smart Reminders", desc: "Hydration alerts, rest timers between sets, and daily workout reminders." },
  { icon: "🎨", title: "Themed UI Modes", desc: "Each training path transforms the entire app with unique colors and aura effects." },
];

export default function LandingPage() {
  const { setTheme } = useTheme();

  return (
    <div style={{ minHeight: "100vh", position: "relative", overflow: "hidden" }}>
      {/* Ambient BG */}
      <div
        className="aura-pulse"
        style={{
          position: "fixed",
          top: "-50%",
          left: "-20%",
          width: "140%",
          height: "140%",
          background: `radial-gradient(ellipse at 30% 20%, var(--theme-aura) 0%, transparent 60%),
                        radial-gradient(ellipse at 70% 80%, rgba(123,47,247,0.04) 0%, transparent 60%)`,
          pointerEvents: "none",
          zIndex: 0,
        }}
      />

      {/* Hero Section */}
      <section
        style={{
          position: "relative",
          zIndex: 1,
          display: "flex",
          flexDirection: "column",
          alignItems: "center",
          justifyContent: "center",
          minHeight: "100vh",
          textAlign: "center",
          padding: "0 24px",
        }}
      >
        <div className="animate-slide-up" style={{ maxWidth: 800 }}>
          <div
            style={{
              display: "inline-block",
              padding: "6px 16px",
              borderRadius: 20,
              background: "var(--theme-aura)",
              border: "1px solid rgba(255,255,255,0.06)",
              fontSize: 13,
              fontWeight: 500,
              color: "var(--primary)",
              marginBottom: 24,
            }}
          >
            ⚡ AI-Powered Anime Fitness
          </div>

          <h1
            style={{
              fontSize: "clamp(40px, 7vw, 72px)",
              fontWeight: 900,
              lineHeight: 1.08,
              letterSpacing: "-2px",
              marginBottom: 20,
            }}
          >
            Train Like A{" "}
            <span className="gradient-text">Legend</span>
          </h1>

          <p
            style={{
              fontSize: 18,
              color: "var(--muted-foreground)",
              maxWidth: 560,
              margin: "0 auto 40px",
              lineHeight: 1.7,
            }}
          >
            Choose your anime training path. Get AI-powered workout plans, personalized nutrition,
            real-time progress tracking, and level up like an RPG character.
          </p>

          <div style={{ display: "flex", gap: 16, justifyContent: "center", flexWrap: "wrap" }}>
            <Link href="/dashboard">
              <button className="btn-primary" style={{ fontSize: 16, padding: "14px 36px" }}>
                Start Training →
              </button>
            </Link>
            <Link href="/workout">
              <button className="btn-outline" style={{ fontSize: 16, padding: "14px 36px" }}>
                Browse Workouts
              </button>
            </Link>
          </div>
        </div>

        {/* Scroll hint */}
        <div
          className="animate-float"
          style={{
            position: "absolute",
            bottom: 40,
            color: "var(--muted-foreground)",
            fontSize: 13,
            display: "flex",
            flexDirection: "column",
            alignItems: "center",
            gap: 8,
          }}
        >
          <span>Scroll to explore</span>
          <span style={{ fontSize: 20 }}>↓</span>
        </div>
      </section>

      {/* Choose Your Path */}
      <section style={{ position: "relative", zIndex: 1, padding: "80px 24px", maxWidth: 1200, margin: "0 auto" }}>
        <h2
          style={{
            textAlign: "center",
            fontSize: 36,
            fontWeight: 800,
            marginBottom: 12,
            letterSpacing: "-1px",
          }}
        >
          Choose Your <span className="gradient-text">Training Path</span>
        </h2>
        <p style={{ textAlign: "center", color: "var(--muted-foreground)", marginBottom: 48, fontSize: 16 }}>
          Each path transforms your entire experience with unique workouts and themed UI.
        </p>

        <div
          style={{
            display: "grid",
            gridTemplateColumns: "repeat(auto-fit, minmax(260px, 1fr))",
            gap: 20,
          }}
        >
          {(Object.keys(THEME_CONFIGS) as WorkoutTheme[]).map((key) => {
            const cfg = THEME_CONFIGS[key];
            return (
              <Link href="/dashboard" key={key} style={{ textDecoration: "none" }}>
                <div
                  className="glass-card"
                  onClick={() => setTheme(key)}
                  style={{
                    padding: 28,
                    cursor: "pointer",
                    textAlign: "center",
                  }}
                >
                  <div style={{ fontSize: 48, marginBottom: 16 }}>{cfg.icon}</div>
                  <h3 style={{ fontSize: 20, fontWeight: 700, color: cfg.colors.primary, marginBottom: 8 }}>
                    {cfg.label}
                  </h3>
                  <p style={{ fontSize: 14, color: "var(--muted-foreground)", lineHeight: 1.6 }}>
                    {cfg.tagline}
                  </p>
                  <div
                    style={{
                      marginTop: 16,
                      fontSize: 12,
                      fontWeight: 600,
                      color: cfg.colors.primary,
                      opacity: 0.7,
                    }}
                  >
                    {cfg.style}
                  </div>
                </div>
              </Link>
            );
          })}
        </div>
      </section>

      {/* Features */}
      <section style={{ position: "relative", zIndex: 1, padding: "60px 24px 100px", maxWidth: 1200, margin: "0 auto" }}>
        <h2
          style={{
            textAlign: "center",
            fontSize: 36,
            fontWeight: 800,
            marginBottom: 48,
            letterSpacing: "-1px",
          }}
        >
          Packed With <span className="gradient-text">Features</span>
        </h2>

        <div
          style={{
            display: "grid",
            gridTemplateColumns: "repeat(auto-fit, minmax(300px, 1fr))",
            gap: 20,
          }}
        >
          {FEATURES.map((f, i) => (
            <div
              key={i}
              className="glass-card"
              style={{ padding: 28, animationDelay: `${i * 0.1}s` }}
            >
              <div style={{ fontSize: 32, marginBottom: 14 }}>{f.icon}</div>
              <h3 style={{ fontSize: 18, fontWeight: 700, marginBottom: 8 }}>{f.title}</h3>
              <p style={{ fontSize: 14, color: "var(--muted-foreground)", lineHeight: 1.7 }}>
                {f.desc}
              </p>
            </div>
          ))}
        </div>
      </section>

      {/* Footer */}
      <footer
        style={{
          borderTop: "1px solid rgba(255,255,255,0.04)",
          textAlign: "center",
          padding: "32px 24px",
          fontSize: 13,
          color: "var(--muted-foreground)",
        }}
      >
        Built with ⚡ by FitSaga AI — Train. Level Up. Dominate.
      </footer>
    </div>
  );
}
