
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `WorkoutProgress` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/client"
import type * as $Enums from "../enums"
import type * as Prisma from "../internal/prismaNamespace"

/**
 * Model WorkoutProgress
 * 
 */
export type WorkoutProgressModel = runtime.Types.Result.DefaultSelection<Prisma.$WorkoutProgressPayload>

export type AggregateWorkoutProgress = {
  _count: WorkoutProgressCountAggregateOutputType | null
  _avg: WorkoutProgressAvgAggregateOutputType | null
  _sum: WorkoutProgressSumAggregateOutputType | null
  _min: WorkoutProgressMinAggregateOutputType | null
  _max: WorkoutProgressMaxAggregateOutputType | null
}

export type WorkoutProgressAvgAggregateOutputType = {
  caloriesBurned: number | null
  exercisesCompleted: number | null
}

export type WorkoutProgressSumAggregateOutputType = {
  caloriesBurned: number | null
  exercisesCompleted: number | null
}

export type WorkoutProgressMinAggregateOutputType = {
  id: string | null
  userId: string | null
  date: Date | null
  workoutCompleted: boolean | null
  caloriesBurned: number | null
  exercisesCompleted: number | null
  workoutTheme: string | null
  createdAt: Date | null
}

export type WorkoutProgressMaxAggregateOutputType = {
  id: string | null
  userId: string | null
  date: Date | null
  workoutCompleted: boolean | null
  caloriesBurned: number | null
  exercisesCompleted: number | null
  workoutTheme: string | null
  createdAt: Date | null
}

export type WorkoutProgressCountAggregateOutputType = {
  id: number
  userId: number
  date: number
  workoutCompleted: number
  caloriesBurned: number
  exercisesCompleted: number
  workoutTheme: number
  createdAt: number
  _all: number
}


export type WorkoutProgressAvgAggregateInputType = {
  caloriesBurned?: true
  exercisesCompleted?: true
}

export type WorkoutProgressSumAggregateInputType = {
  caloriesBurned?: true
  exercisesCompleted?: true
}

export type WorkoutProgressMinAggregateInputType = {
  id?: true
  userId?: true
  date?: true
  workoutCompleted?: true
  caloriesBurned?: true
  exercisesCompleted?: true
  workoutTheme?: true
  createdAt?: true
}

export type WorkoutProgressMaxAggregateInputType = {
  id?: true
  userId?: true
  date?: true
  workoutCompleted?: true
  caloriesBurned?: true
  exercisesCompleted?: true
  workoutTheme?: true
  createdAt?: true
}

export type WorkoutProgressCountAggregateInputType = {
  id?: true
  userId?: true
  date?: true
  workoutCompleted?: true
  caloriesBurned?: true
  exercisesCompleted?: true
  workoutTheme?: true
  createdAt?: true
  _all?: true
}

export type WorkoutProgressAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which WorkoutProgress to aggregate.
   */
  where?: Prisma.WorkoutProgressWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of WorkoutProgresses to fetch.
   */
  orderBy?: Prisma.WorkoutProgressOrderByWithRelationInput | Prisma.WorkoutProgressOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.WorkoutProgressWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` WorkoutProgresses from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` WorkoutProgresses.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned WorkoutProgresses
  **/
  _count?: true | WorkoutProgressCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to average
  **/
  _avg?: WorkoutProgressAvgAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to sum
  **/
  _sum?: WorkoutProgressSumAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: WorkoutProgressMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: WorkoutProgressMaxAggregateInputType
}

export type GetWorkoutProgressAggregateType<T extends WorkoutProgressAggregateArgs> = {
      [P in keyof T & keyof AggregateWorkoutProgress]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateWorkoutProgress[P]>
    : Prisma.GetScalarType<T[P], AggregateWorkoutProgress[P]>
}




export type WorkoutProgressGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.WorkoutProgressWhereInput
  orderBy?: Prisma.WorkoutProgressOrderByWithAggregationInput | Prisma.WorkoutProgressOrderByWithAggregationInput[]
  by: Prisma.WorkoutProgressScalarFieldEnum[] | Prisma.WorkoutProgressScalarFieldEnum
  having?: Prisma.WorkoutProgressScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: WorkoutProgressCountAggregateInputType | true
  _avg?: WorkoutProgressAvgAggregateInputType
  _sum?: WorkoutProgressSumAggregateInputType
  _min?: WorkoutProgressMinAggregateInputType
  _max?: WorkoutProgressMaxAggregateInputType
}

export type WorkoutProgressGroupByOutputType = {
  id: string
  userId: string
  date: Date
  workoutCompleted: boolean
  caloriesBurned: number
  exercisesCompleted: number
  workoutTheme: string
  createdAt: Date
  _count: WorkoutProgressCountAggregateOutputType | null
  _avg: WorkoutProgressAvgAggregateOutputType | null
  _sum: WorkoutProgressSumAggregateOutputType | null
  _min: WorkoutProgressMinAggregateOutputType | null
  _max: WorkoutProgressMaxAggregateOutputType | null
}

type GetWorkoutProgressGroupByPayload<T extends WorkoutProgressGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<WorkoutProgressGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof WorkoutProgressGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], WorkoutProgressGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], WorkoutProgressGroupByOutputType[P]>
      }
    >
  >



export type WorkoutProgressWhereInput = {
  AND?: Prisma.WorkoutProgressWhereInput | Prisma.WorkoutProgressWhereInput[]
  OR?: Prisma.WorkoutProgressWhereInput[]
  NOT?: Prisma.WorkoutProgressWhereInput | Prisma.WorkoutProgressWhereInput[]
  id?: Prisma.StringFilter<"WorkoutProgress"> | string
  userId?: Prisma.StringFilter<"WorkoutProgress"> | string
  date?: Prisma.DateTimeFilter<"WorkoutProgress"> | Date | string
  workoutCompleted?: Prisma.BoolFilter<"WorkoutProgress"> | boolean
  caloriesBurned?: Prisma.FloatFilter<"WorkoutProgress"> | number
  exercisesCompleted?: Prisma.IntFilter<"WorkoutProgress"> | number
  workoutTheme?: Prisma.StringFilter<"WorkoutProgress"> | string
  createdAt?: Prisma.DateTimeFilter<"WorkoutProgress"> | Date | string
  user?: Prisma.XOR<Prisma.UserScalarRelationFilter, Prisma.UserWhereInput>
}

export type WorkoutProgressOrderByWithRelationInput = {
  id?: Prisma.SortOrder
  userId?: Prisma.SortOrder
  date?: Prisma.SortOrder
  workoutCompleted?: Prisma.SortOrder
  caloriesBurned?: Prisma.SortOrder
  exercisesCompleted?: Prisma.SortOrder
  workoutTheme?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  user?: Prisma.UserOrderByWithRelationInput
}

export type WorkoutProgressWhereUniqueInput = Prisma.AtLeast<{
  id?: string
  AND?: Prisma.WorkoutProgressWhereInput | Prisma.WorkoutProgressWhereInput[]
  OR?: Prisma.WorkoutProgressWhereInput[]
  NOT?: Prisma.WorkoutProgressWhereInput | Prisma.WorkoutProgressWhereInput[]
  userId?: Prisma.StringFilter<"WorkoutProgress"> | string
  date?: Prisma.DateTimeFilter<"WorkoutProgress"> | Date | string
  workoutCompleted?: Prisma.BoolFilter<"WorkoutProgress"> | boolean
  caloriesBurned?: Prisma.FloatFilter<"WorkoutProgress"> | number
  exercisesCompleted?: Prisma.IntFilter<"WorkoutProgress"> | number
  workoutTheme?: Prisma.StringFilter<"WorkoutProgress"> | string
  createdAt?: Prisma.DateTimeFilter<"WorkoutProgress"> | Date | string
  user?: Prisma.XOR<Prisma.UserScalarRelationFilter, Prisma.UserWhereInput>
}, "id">

export type WorkoutProgressOrderByWithAggregationInput = {
  id?: Prisma.SortOrder
  userId?: Prisma.SortOrder
  date?: Prisma.SortOrder
  workoutCompleted?: Prisma.SortOrder
  caloriesBurned?: Prisma.SortOrder
  exercisesCompleted?: Prisma.SortOrder
  workoutTheme?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  _count?: Prisma.WorkoutProgressCountOrderByAggregateInput
  _avg?: Prisma.WorkoutProgressAvgOrderByAggregateInput
  _max?: Prisma.WorkoutProgressMaxOrderByAggregateInput
  _min?: Prisma.WorkoutProgressMinOrderByAggregateInput
  _sum?: Prisma.WorkoutProgressSumOrderByAggregateInput
}

export type WorkoutProgressScalarWhereWithAggregatesInput = {
  AND?: Prisma.WorkoutProgressScalarWhereWithAggregatesInput | Prisma.WorkoutProgressScalarWhereWithAggregatesInput[]
  OR?: Prisma.WorkoutProgressScalarWhereWithAggregatesInput[]
  NOT?: Prisma.WorkoutProgressScalarWhereWithAggregatesInput | Prisma.WorkoutProgressScalarWhereWithAggregatesInput[]
  id?: Prisma.StringWithAggregatesFilter<"WorkoutProgress"> | string
  userId?: Prisma.StringWithAggregatesFilter<"WorkoutProgress"> | string
  date?: Prisma.DateTimeWithAggregatesFilter<"WorkoutProgress"> | Date | string
  workoutCompleted?: Prisma.BoolWithAggregatesFilter<"WorkoutProgress"> | boolean
  caloriesBurned?: Prisma.FloatWithAggregatesFilter<"WorkoutProgress"> | number
  exercisesCompleted?: Prisma.IntWithAggregatesFilter<"WorkoutProgress"> | number
  workoutTheme?: Prisma.StringWithAggregatesFilter<"WorkoutProgress"> | string
  createdAt?: Prisma.DateTimeWithAggregatesFilter<"WorkoutProgress"> | Date | string
}

export type WorkoutProgressCreateInput = {
  id?: string
  date?: Date | string
  workoutCompleted?: boolean
  caloriesBurned?: number
  exercisesCompleted?: number
  workoutTheme: string
  createdAt?: Date | string
  user: Prisma.UserCreateNestedOneWithoutWorkoutProgressInput
}

export type WorkoutProgressUncheckedCreateInput = {
  id?: string
  userId: string
  date?: Date | string
  workoutCompleted?: boolean
  caloriesBurned?: number
  exercisesCompleted?: number
  workoutTheme: string
  createdAt?: Date | string
}

export type WorkoutProgressUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  date?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  workoutCompleted?: Prisma.BoolFieldUpdateOperationsInput | boolean
  caloriesBurned?: Prisma.FloatFieldUpdateOperationsInput | number
  exercisesCompleted?: Prisma.IntFieldUpdateOperationsInput | number
  workoutTheme?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  user?: Prisma.UserUpdateOneRequiredWithoutWorkoutProgressNestedInput
}

export type WorkoutProgressUncheckedUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  userId?: Prisma.StringFieldUpdateOperationsInput | string
  date?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  workoutCompleted?: Prisma.BoolFieldUpdateOperationsInput | boolean
  caloriesBurned?: Prisma.FloatFieldUpdateOperationsInput | number
  exercisesCompleted?: Prisma.IntFieldUpdateOperationsInput | number
  workoutTheme?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type WorkoutProgressCreateManyInput = {
  id?: string
  userId: string
  date?: Date | string
  workoutCompleted?: boolean
  caloriesBurned?: number
  exercisesCompleted?: number
  workoutTheme: string
  createdAt?: Date | string
}

export type WorkoutProgressUpdateManyMutationInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  date?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  workoutCompleted?: Prisma.BoolFieldUpdateOperationsInput | boolean
  caloriesBurned?: Prisma.FloatFieldUpdateOperationsInput | number
  exercisesCompleted?: Prisma.IntFieldUpdateOperationsInput | number
  workoutTheme?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type WorkoutProgressUncheckedUpdateManyInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  userId?: Prisma.StringFieldUpdateOperationsInput | string
  date?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  workoutCompleted?: Prisma.BoolFieldUpdateOperationsInput | boolean
  caloriesBurned?: Prisma.FloatFieldUpdateOperationsInput | number
  exercisesCompleted?: Prisma.IntFieldUpdateOperationsInput | number
  workoutTheme?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type WorkoutProgressListRelationFilter = {
  every?: Prisma.WorkoutProgressWhereInput
  some?: Prisma.WorkoutProgressWhereInput
  none?: Prisma.WorkoutProgressWhereInput
}

export type WorkoutProgressOrderByRelationAggregateInput = {
  _count?: Prisma.SortOrder
}

export type WorkoutProgressCountOrderByAggregateInput = {
  id?: Prisma.SortOrder
  userId?: Prisma.SortOrder
  date?: Prisma.SortOrder
  workoutCompleted?: Prisma.SortOrder
  caloriesBurned?: Prisma.SortOrder
  exercisesCompleted?: Prisma.SortOrder
  workoutTheme?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
}

export type WorkoutProgressAvgOrderByAggregateInput = {
  caloriesBurned?: Prisma.SortOrder
  exercisesCompleted?: Prisma.SortOrder
}

export type WorkoutProgressMaxOrderByAggregateInput = {
  id?: Prisma.SortOrder
  userId?: Prisma.SortOrder
  date?: Prisma.SortOrder
  workoutCompleted?: Prisma.SortOrder
  caloriesBurned?: Prisma.SortOrder
  exercisesCompleted?: Prisma.SortOrder
  workoutTheme?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
}

export type WorkoutProgressMinOrderByAggregateInput = {
  id?: Prisma.SortOrder
  userId?: Prisma.SortOrder
  date?: Prisma.SortOrder
  workoutCompleted?: Prisma.SortOrder
  caloriesBurned?: Prisma.SortOrder
  exercisesCompleted?: Prisma.SortOrder
  workoutTheme?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
}

export type WorkoutProgressSumOrderByAggregateInput = {
  caloriesBurned?: Prisma.SortOrder
  exercisesCompleted?: Prisma.SortOrder
}

export type WorkoutProgressCreateNestedManyWithoutUserInput = {
  create?: Prisma.XOR<Prisma.WorkoutProgressCreateWithoutUserInput, Prisma.WorkoutProgressUncheckedCreateWithoutUserInput> | Prisma.WorkoutProgressCreateWithoutUserInput[] | Prisma.WorkoutProgressUncheckedCreateWithoutUserInput[]
  connectOrCreate?: Prisma.WorkoutProgressCreateOrConnectWithoutUserInput | Prisma.WorkoutProgressCreateOrConnectWithoutUserInput[]
  createMany?: Prisma.WorkoutProgressCreateManyUserInputEnvelope
  connect?: Prisma.WorkoutProgressWhereUniqueInput | Prisma.WorkoutProgressWhereUniqueInput[]
}

export type WorkoutProgressUncheckedCreateNestedManyWithoutUserInput = {
  create?: Prisma.XOR<Prisma.WorkoutProgressCreateWithoutUserInput, Prisma.WorkoutProgressUncheckedCreateWithoutUserInput> | Prisma.WorkoutProgressCreateWithoutUserInput[] | Prisma.WorkoutProgressUncheckedCreateWithoutUserInput[]
  connectOrCreate?: Prisma.WorkoutProgressCreateOrConnectWithoutUserInput | Prisma.WorkoutProgressCreateOrConnectWithoutUserInput[]
  createMany?: Prisma.WorkoutProgressCreateManyUserInputEnvelope
  connect?: Prisma.WorkoutProgressWhereUniqueInput | Prisma.WorkoutProgressWhereUniqueInput[]
}

export type WorkoutProgressUpdateManyWithoutUserNestedInput = {
  create?: Prisma.XOR<Prisma.WorkoutProgressCreateWithoutUserInput, Prisma.WorkoutProgressUncheckedCreateWithoutUserInput> | Prisma.WorkoutProgressCreateWithoutUserInput[] | Prisma.WorkoutProgressUncheckedCreateWithoutUserInput[]
  connectOrCreate?: Prisma.WorkoutProgressCreateOrConnectWithoutUserInput | Prisma.WorkoutProgressCreateOrConnectWithoutUserInput[]
  upsert?: Prisma.WorkoutProgressUpsertWithWhereUniqueWithoutUserInput | Prisma.WorkoutProgressUpsertWithWhereUniqueWithoutUserInput[]
  createMany?: Prisma.WorkoutProgressCreateManyUserInputEnvelope
  set?: Prisma.WorkoutProgressWhereUniqueInput | Prisma.WorkoutProgressWhereUniqueInput[]
  disconnect?: Prisma.WorkoutProgressWhereUniqueInput | Prisma.WorkoutProgressWhereUniqueInput[]
  delete?: Prisma.WorkoutProgressWhereUniqueInput | Prisma.WorkoutProgressWhereUniqueInput[]
  connect?: Prisma.WorkoutProgressWhereUniqueInput | Prisma.WorkoutProgressWhereUniqueInput[]
  update?: Prisma.WorkoutProgressUpdateWithWhereUniqueWithoutUserInput | Prisma.WorkoutProgressUpdateWithWhereUniqueWithoutUserInput[]
  updateMany?: Prisma.WorkoutProgressUpdateManyWithWhereWithoutUserInput | Prisma.WorkoutProgressUpdateManyWithWhereWithoutUserInput[]
  deleteMany?: Prisma.WorkoutProgressScalarWhereInput | Prisma.WorkoutProgressScalarWhereInput[]
}

export type WorkoutProgressUncheckedUpdateManyWithoutUserNestedInput = {
  create?: Prisma.XOR<Prisma.WorkoutProgressCreateWithoutUserInput, Prisma.WorkoutProgressUncheckedCreateWithoutUserInput> | Prisma.WorkoutProgressCreateWithoutUserInput[] | Prisma.WorkoutProgressUncheckedCreateWithoutUserInput[]
  connectOrCreate?: Prisma.WorkoutProgressCreateOrConnectWithoutUserInput | Prisma.WorkoutProgressCreateOrConnectWithoutUserInput[]
  upsert?: Prisma.WorkoutProgressUpsertWithWhereUniqueWithoutUserInput | Prisma.WorkoutProgressUpsertWithWhereUniqueWithoutUserInput[]
  createMany?: Prisma.WorkoutProgressCreateManyUserInputEnvelope
  set?: Prisma.WorkoutProgressWhereUniqueInput | Prisma.WorkoutProgressWhereUniqueInput[]
  disconnect?: Prisma.WorkoutProgressWhereUniqueInput | Prisma.WorkoutProgressWhereUniqueInput[]
  delete?: Prisma.WorkoutProgressWhereUniqueInput | Prisma.WorkoutProgressWhereUniqueInput[]
  connect?: Prisma.WorkoutProgressWhereUniqueInput | Prisma.WorkoutProgressWhereUniqueInput[]
  update?: Prisma.WorkoutProgressUpdateWithWhereUniqueWithoutUserInput | Prisma.WorkoutProgressUpdateWithWhereUniqueWithoutUserInput[]
  updateMany?: Prisma.WorkoutProgressUpdateManyWithWhereWithoutUserInput | Prisma.WorkoutProgressUpdateManyWithWhereWithoutUserInput[]
  deleteMany?: Prisma.WorkoutProgressScalarWhereInput | Prisma.WorkoutProgressScalarWhereInput[]
}

export type BoolFieldUpdateOperationsInput = {
  set?: boolean
}

export type WorkoutProgressCreateWithoutUserInput = {
  id?: string
  date?: Date | string
  workoutCompleted?: boolean
  caloriesBurned?: number
  exercisesCompleted?: number
  workoutTheme: string
  createdAt?: Date | string
}

export type WorkoutProgressUncheckedCreateWithoutUserInput = {
  id?: string
  date?: Date | string
  workoutCompleted?: boolean
  caloriesBurned?: number
  exercisesCompleted?: number
  workoutTheme: string
  createdAt?: Date | string
}

export type WorkoutProgressCreateOrConnectWithoutUserInput = {
  where: Prisma.WorkoutProgressWhereUniqueInput
  create: Prisma.XOR<Prisma.WorkoutProgressCreateWithoutUserInput, Prisma.WorkoutProgressUncheckedCreateWithoutUserInput>
}

export type WorkoutProgressCreateManyUserInputEnvelope = {
  data: Prisma.WorkoutProgressCreateManyUserInput | Prisma.WorkoutProgressCreateManyUserInput[]
  skipDuplicates?: boolean
}

export type WorkoutProgressUpsertWithWhereUniqueWithoutUserInput = {
  where: Prisma.WorkoutProgressWhereUniqueInput
  update: Prisma.XOR<Prisma.WorkoutProgressUpdateWithoutUserInput, Prisma.WorkoutProgressUncheckedUpdateWithoutUserInput>
  create: Prisma.XOR<Prisma.WorkoutProgressCreateWithoutUserInput, Prisma.WorkoutProgressUncheckedCreateWithoutUserInput>
}

export type WorkoutProgressUpdateWithWhereUniqueWithoutUserInput = {
  where: Prisma.WorkoutProgressWhereUniqueInput
  data: Prisma.XOR<Prisma.WorkoutProgressUpdateWithoutUserInput, Prisma.WorkoutProgressUncheckedUpdateWithoutUserInput>
}

export type WorkoutProgressUpdateManyWithWhereWithoutUserInput = {
  where: Prisma.WorkoutProgressScalarWhereInput
  data: Prisma.XOR<Prisma.WorkoutProgressUpdateManyMutationInput, Prisma.WorkoutProgressUncheckedUpdateManyWithoutUserInput>
}

export type WorkoutProgressScalarWhereInput = {
  AND?: Prisma.WorkoutProgressScalarWhereInput | Prisma.WorkoutProgressScalarWhereInput[]
  OR?: Prisma.WorkoutProgressScalarWhereInput[]
  NOT?: Prisma.WorkoutProgressScalarWhereInput | Prisma.WorkoutProgressScalarWhereInput[]
  id?: Prisma.StringFilter<"WorkoutProgress"> | string
  userId?: Prisma.StringFilter<"WorkoutProgress"> | string
  date?: Prisma.DateTimeFilter<"WorkoutProgress"> | Date | string
  workoutCompleted?: Prisma.BoolFilter<"WorkoutProgress"> | boolean
  caloriesBurned?: Prisma.FloatFilter<"WorkoutProgress"> | number
  exercisesCompleted?: Prisma.IntFilter<"WorkoutProgress"> | number
  workoutTheme?: Prisma.StringFilter<"WorkoutProgress"> | string
  createdAt?: Prisma.DateTimeFilter<"WorkoutProgress"> | Date | string
}

export type WorkoutProgressCreateManyUserInput = {
  id?: string
  date?: Date | string
  workoutCompleted?: boolean
  caloriesBurned?: number
  exercisesCompleted?: number
  workoutTheme: string
  createdAt?: Date | string
}

export type WorkoutProgressUpdateWithoutUserInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  date?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  workoutCompleted?: Prisma.BoolFieldUpdateOperationsInput | boolean
  caloriesBurned?: Prisma.FloatFieldUpdateOperationsInput | number
  exercisesCompleted?: Prisma.IntFieldUpdateOperationsInput | number
  workoutTheme?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type WorkoutProgressUncheckedUpdateWithoutUserInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  date?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  workoutCompleted?: Prisma.BoolFieldUpdateOperationsInput | boolean
  caloriesBurned?: Prisma.FloatFieldUpdateOperationsInput | number
  exercisesCompleted?: Prisma.IntFieldUpdateOperationsInput | number
  workoutTheme?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type WorkoutProgressUncheckedUpdateManyWithoutUserInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  date?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  workoutCompleted?: Prisma.BoolFieldUpdateOperationsInput | boolean
  caloriesBurned?: Prisma.FloatFieldUpdateOperationsInput | number
  exercisesCompleted?: Prisma.IntFieldUpdateOperationsInput | number
  workoutTheme?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}



export type WorkoutProgressSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  userId?: boolean
  date?: boolean
  workoutCompleted?: boolean
  caloriesBurned?: boolean
  exercisesCompleted?: boolean
  workoutTheme?: boolean
  createdAt?: boolean
  user?: boolean | Prisma.UserDefaultArgs<ExtArgs>
}, ExtArgs["result"]["workoutProgress"]>

export type WorkoutProgressSelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  userId?: boolean
  date?: boolean
  workoutCompleted?: boolean
  caloriesBurned?: boolean
  exercisesCompleted?: boolean
  workoutTheme?: boolean
  createdAt?: boolean
  user?: boolean | Prisma.UserDefaultArgs<ExtArgs>
}, ExtArgs["result"]["workoutProgress"]>

export type WorkoutProgressSelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  userId?: boolean
  date?: boolean
  workoutCompleted?: boolean
  caloriesBurned?: boolean
  exercisesCompleted?: boolean
  workoutTheme?: boolean
  createdAt?: boolean
  user?: boolean | Prisma.UserDefaultArgs<ExtArgs>
}, ExtArgs["result"]["workoutProgress"]>

export type WorkoutProgressSelectScalar = {
  id?: boolean
  userId?: boolean
  date?: boolean
  workoutCompleted?: boolean
  caloriesBurned?: boolean
  exercisesCompleted?: boolean
  workoutTheme?: boolean
  createdAt?: boolean
}

export type WorkoutProgressOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"id" | "userId" | "date" | "workoutCompleted" | "caloriesBurned" | "exercisesCompleted" | "workoutTheme" | "createdAt", ExtArgs["result"]["workoutProgress"]>
export type WorkoutProgressInclude<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  user?: boolean | Prisma.UserDefaultArgs<ExtArgs>
}
export type WorkoutProgressIncludeCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  user?: boolean | Prisma.UserDefaultArgs<ExtArgs>
}
export type WorkoutProgressIncludeUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  user?: boolean | Prisma.UserDefaultArgs<ExtArgs>
}

export type $WorkoutProgressPayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "WorkoutProgress"
  objects: {
    user: Prisma.$UserPayload<ExtArgs>
  }
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    id: string
    userId: string
    date: Date
    workoutCompleted: boolean
    caloriesBurned: number
    exercisesCompleted: number
    workoutTheme: string
    createdAt: Date
  }, ExtArgs["result"]["workoutProgress"]>
  composites: {}
}

export type WorkoutProgressGetPayload<S extends boolean | null | undefined | WorkoutProgressDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$WorkoutProgressPayload, S>

export type WorkoutProgressCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<WorkoutProgressFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: WorkoutProgressCountAggregateInputType | true
  }

export interface WorkoutProgressDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['WorkoutProgress'], meta: { name: 'WorkoutProgress' } }
  /**
   * Find zero or one WorkoutProgress that matches the filter.
   * @param {WorkoutProgressFindUniqueArgs} args - Arguments to find a WorkoutProgress
   * @example
   * // Get one WorkoutProgress
   * const workoutProgress = await prisma.workoutProgress.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends WorkoutProgressFindUniqueArgs>(args: Prisma.SelectSubset<T, WorkoutProgressFindUniqueArgs<ExtArgs>>): Prisma.Prisma__WorkoutProgressClient<runtime.Types.Result.GetResult<Prisma.$WorkoutProgressPayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one WorkoutProgress that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {WorkoutProgressFindUniqueOrThrowArgs} args - Arguments to find a WorkoutProgress
   * @example
   * // Get one WorkoutProgress
   * const workoutProgress = await prisma.workoutProgress.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends WorkoutProgressFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, WorkoutProgressFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__WorkoutProgressClient<runtime.Types.Result.GetResult<Prisma.$WorkoutProgressPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first WorkoutProgress that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {WorkoutProgressFindFirstArgs} args - Arguments to find a WorkoutProgress
   * @example
   * // Get one WorkoutProgress
   * const workoutProgress = await prisma.workoutProgress.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends WorkoutProgressFindFirstArgs>(args?: Prisma.SelectSubset<T, WorkoutProgressFindFirstArgs<ExtArgs>>): Prisma.Prisma__WorkoutProgressClient<runtime.Types.Result.GetResult<Prisma.$WorkoutProgressPayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first WorkoutProgress that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {WorkoutProgressFindFirstOrThrowArgs} args - Arguments to find a WorkoutProgress
   * @example
   * // Get one WorkoutProgress
   * const workoutProgress = await prisma.workoutProgress.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends WorkoutProgressFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, WorkoutProgressFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__WorkoutProgressClient<runtime.Types.Result.GetResult<Prisma.$WorkoutProgressPayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more WorkoutProgresses that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {WorkoutProgressFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all WorkoutProgresses
   * const workoutProgresses = await prisma.workoutProgress.findMany()
   * 
   * // Get first 10 WorkoutProgresses
   * const workoutProgresses = await prisma.workoutProgress.findMany({ take: 10 })
   * 
   * // Only select the `id`
   * const workoutProgressWithIdOnly = await prisma.workoutProgress.findMany({ select: { id: true } })
   * 
   */
  findMany<T extends WorkoutProgressFindManyArgs>(args?: Prisma.SelectSubset<T, WorkoutProgressFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$WorkoutProgressPayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a WorkoutProgress.
   * @param {WorkoutProgressCreateArgs} args - Arguments to create a WorkoutProgress.
   * @example
   * // Create one WorkoutProgress
   * const WorkoutProgress = await prisma.workoutProgress.create({
   *   data: {
   *     // ... data to create a WorkoutProgress
   *   }
   * })
   * 
   */
  create<T extends WorkoutProgressCreateArgs>(args: Prisma.SelectSubset<T, WorkoutProgressCreateArgs<ExtArgs>>): Prisma.Prisma__WorkoutProgressClient<runtime.Types.Result.GetResult<Prisma.$WorkoutProgressPayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many WorkoutProgresses.
   * @param {WorkoutProgressCreateManyArgs} args - Arguments to create many WorkoutProgresses.
   * @example
   * // Create many WorkoutProgresses
   * const workoutProgress = await prisma.workoutProgress.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends WorkoutProgressCreateManyArgs>(args?: Prisma.SelectSubset<T, WorkoutProgressCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many WorkoutProgresses and returns the data saved in the database.
   * @param {WorkoutProgressCreateManyAndReturnArgs} args - Arguments to create many WorkoutProgresses.
   * @example
   * // Create many WorkoutProgresses
   * const workoutProgress = await prisma.workoutProgress.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many WorkoutProgresses and only return the `id`
   * const workoutProgressWithIdOnly = await prisma.workoutProgress.createManyAndReturn({
   *   select: { id: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends WorkoutProgressCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, WorkoutProgressCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$WorkoutProgressPayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a WorkoutProgress.
   * @param {WorkoutProgressDeleteArgs} args - Arguments to delete one WorkoutProgress.
   * @example
   * // Delete one WorkoutProgress
   * const WorkoutProgress = await prisma.workoutProgress.delete({
   *   where: {
   *     // ... filter to delete one WorkoutProgress
   *   }
   * })
   * 
   */
  delete<T extends WorkoutProgressDeleteArgs>(args: Prisma.SelectSubset<T, WorkoutProgressDeleteArgs<ExtArgs>>): Prisma.Prisma__WorkoutProgressClient<runtime.Types.Result.GetResult<Prisma.$WorkoutProgressPayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one WorkoutProgress.
   * @param {WorkoutProgressUpdateArgs} args - Arguments to update one WorkoutProgress.
   * @example
   * // Update one WorkoutProgress
   * const workoutProgress = await prisma.workoutProgress.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends WorkoutProgressUpdateArgs>(args: Prisma.SelectSubset<T, WorkoutProgressUpdateArgs<ExtArgs>>): Prisma.Prisma__WorkoutProgressClient<runtime.Types.Result.GetResult<Prisma.$WorkoutProgressPayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more WorkoutProgresses.
   * @param {WorkoutProgressDeleteManyArgs} args - Arguments to filter WorkoutProgresses to delete.
   * @example
   * // Delete a few WorkoutProgresses
   * const { count } = await prisma.workoutProgress.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends WorkoutProgressDeleteManyArgs>(args?: Prisma.SelectSubset<T, WorkoutProgressDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more WorkoutProgresses.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {WorkoutProgressUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many WorkoutProgresses
   * const workoutProgress = await prisma.workoutProgress.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends WorkoutProgressUpdateManyArgs>(args: Prisma.SelectSubset<T, WorkoutProgressUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more WorkoutProgresses and returns the data updated in the database.
   * @param {WorkoutProgressUpdateManyAndReturnArgs} args - Arguments to update many WorkoutProgresses.
   * @example
   * // Update many WorkoutProgresses
   * const workoutProgress = await prisma.workoutProgress.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more WorkoutProgresses and only return the `id`
   * const workoutProgressWithIdOnly = await prisma.workoutProgress.updateManyAndReturn({
   *   select: { id: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends WorkoutProgressUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, WorkoutProgressUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$WorkoutProgressPayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one WorkoutProgress.
   * @param {WorkoutProgressUpsertArgs} args - Arguments to update or create a WorkoutProgress.
   * @example
   * // Update or create a WorkoutProgress
   * const workoutProgress = await prisma.workoutProgress.upsert({
   *   create: {
   *     // ... data to create a WorkoutProgress
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the WorkoutProgress we want to update
   *   }
   * })
   */
  upsert<T extends WorkoutProgressUpsertArgs>(args: Prisma.SelectSubset<T, WorkoutProgressUpsertArgs<ExtArgs>>): Prisma.Prisma__WorkoutProgressClient<runtime.Types.Result.GetResult<Prisma.$WorkoutProgressPayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of WorkoutProgresses.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {WorkoutProgressCountArgs} args - Arguments to filter WorkoutProgresses to count.
   * @example
   * // Count the number of WorkoutProgresses
   * const count = await prisma.workoutProgress.count({
   *   where: {
   *     // ... the filter for the WorkoutProgresses we want to count
   *   }
   * })
  **/
  count<T extends WorkoutProgressCountArgs>(
    args?: Prisma.Subset<T, WorkoutProgressCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], WorkoutProgressCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a WorkoutProgress.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {WorkoutProgressAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends WorkoutProgressAggregateArgs>(args: Prisma.Subset<T, WorkoutProgressAggregateArgs>): Prisma.PrismaPromise<GetWorkoutProgressAggregateType<T>>

  /**
   * Group by WorkoutProgress.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {WorkoutProgressGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends WorkoutProgressGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: WorkoutProgressGroupByArgs['orderBy'] }
      : { orderBy?: WorkoutProgressGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, WorkoutProgressGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetWorkoutProgressGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the WorkoutProgress model
 */
readonly fields: WorkoutProgressFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for WorkoutProgress.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__WorkoutProgressClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  user<T extends Prisma.UserDefaultArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.UserDefaultArgs<ExtArgs>>): Prisma.Prisma__UserClient<runtime.Types.Result.GetResult<Prisma.$UserPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | Null, Null, ExtArgs, GlobalOmitOptions>
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the WorkoutProgress model
 */
export interface WorkoutProgressFieldRefs {
  readonly id: Prisma.FieldRef<"WorkoutProgress", 'String'>
  readonly userId: Prisma.FieldRef<"WorkoutProgress", 'String'>
  readonly date: Prisma.FieldRef<"WorkoutProgress", 'DateTime'>
  readonly workoutCompleted: Prisma.FieldRef<"WorkoutProgress", 'Boolean'>
  readonly caloriesBurned: Prisma.FieldRef<"WorkoutProgress", 'Float'>
  readonly exercisesCompleted: Prisma.FieldRef<"WorkoutProgress", 'Int'>
  readonly workoutTheme: Prisma.FieldRef<"WorkoutProgress", 'String'>
  readonly createdAt: Prisma.FieldRef<"WorkoutProgress", 'DateTime'>
}
    

// Custom InputTypes
/**
 * WorkoutProgress findUnique
 */
export type WorkoutProgressFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the WorkoutProgress
   */
  select?: Prisma.WorkoutProgressSelect<ExtArgs> | null
  /**
   * Omit specific fields from the WorkoutProgress
   */
  omit?: Prisma.WorkoutProgressOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.WorkoutProgressInclude<ExtArgs> | null
  /**
   * Filter, which WorkoutProgress to fetch.
   */
  where: Prisma.WorkoutProgressWhereUniqueInput
}

/**
 * WorkoutProgress findUniqueOrThrow
 */
export type WorkoutProgressFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the WorkoutProgress
   */
  select?: Prisma.WorkoutProgressSelect<ExtArgs> | null
  /**
   * Omit specific fields from the WorkoutProgress
   */
  omit?: Prisma.WorkoutProgressOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.WorkoutProgressInclude<ExtArgs> | null
  /**
   * Filter, which WorkoutProgress to fetch.
   */
  where: Prisma.WorkoutProgressWhereUniqueInput
}

/**
 * WorkoutProgress findFirst
 */
export type WorkoutProgressFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the WorkoutProgress
   */
  select?: Prisma.WorkoutProgressSelect<ExtArgs> | null
  /**
   * Omit specific fields from the WorkoutProgress
   */
  omit?: Prisma.WorkoutProgressOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.WorkoutProgressInclude<ExtArgs> | null
  /**
   * Filter, which WorkoutProgress to fetch.
   */
  where?: Prisma.WorkoutProgressWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of WorkoutProgresses to fetch.
   */
  orderBy?: Prisma.WorkoutProgressOrderByWithRelationInput | Prisma.WorkoutProgressOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for WorkoutProgresses.
   */
  cursor?: Prisma.WorkoutProgressWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` WorkoutProgresses from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` WorkoutProgresses.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of WorkoutProgresses.
   */
  distinct?: Prisma.WorkoutProgressScalarFieldEnum | Prisma.WorkoutProgressScalarFieldEnum[]
}

/**
 * WorkoutProgress findFirstOrThrow
 */
export type WorkoutProgressFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the WorkoutProgress
   */
  select?: Prisma.WorkoutProgressSelect<ExtArgs> | null
  /**
   * Omit specific fields from the WorkoutProgress
   */
  omit?: Prisma.WorkoutProgressOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.WorkoutProgressInclude<ExtArgs> | null
  /**
   * Filter, which WorkoutProgress to fetch.
   */
  where?: Prisma.WorkoutProgressWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of WorkoutProgresses to fetch.
   */
  orderBy?: Prisma.WorkoutProgressOrderByWithRelationInput | Prisma.WorkoutProgressOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for WorkoutProgresses.
   */
  cursor?: Prisma.WorkoutProgressWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` WorkoutProgresses from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` WorkoutProgresses.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of WorkoutProgresses.
   */
  distinct?: Prisma.WorkoutProgressScalarFieldEnum | Prisma.WorkoutProgressScalarFieldEnum[]
}

/**
 * WorkoutProgress findMany
 */
export type WorkoutProgressFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the WorkoutProgress
   */
  select?: Prisma.WorkoutProgressSelect<ExtArgs> | null
  /**
   * Omit specific fields from the WorkoutProgress
   */
  omit?: Prisma.WorkoutProgressOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.WorkoutProgressInclude<ExtArgs> | null
  /**
   * Filter, which WorkoutProgresses to fetch.
   */
  where?: Prisma.WorkoutProgressWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of WorkoutProgresses to fetch.
   */
  orderBy?: Prisma.WorkoutProgressOrderByWithRelationInput | Prisma.WorkoutProgressOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing WorkoutProgresses.
   */
  cursor?: Prisma.WorkoutProgressWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` WorkoutProgresses from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` WorkoutProgresses.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of WorkoutProgresses.
   */
  distinct?: Prisma.WorkoutProgressScalarFieldEnum | Prisma.WorkoutProgressScalarFieldEnum[]
}

/**
 * WorkoutProgress create
 */
export type WorkoutProgressCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the WorkoutProgress
   */
  select?: Prisma.WorkoutProgressSelect<ExtArgs> | null
  /**
   * Omit specific fields from the WorkoutProgress
   */
  omit?: Prisma.WorkoutProgressOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.WorkoutProgressInclude<ExtArgs> | null
  /**
   * The data needed to create a WorkoutProgress.
   */
  data: Prisma.XOR<Prisma.WorkoutProgressCreateInput, Prisma.WorkoutProgressUncheckedCreateInput>
}

/**
 * WorkoutProgress createMany
 */
export type WorkoutProgressCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many WorkoutProgresses.
   */
  data: Prisma.WorkoutProgressCreateManyInput | Prisma.WorkoutProgressCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * WorkoutProgress createManyAndReturn
 */
export type WorkoutProgressCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the WorkoutProgress
   */
  select?: Prisma.WorkoutProgressSelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the WorkoutProgress
   */
  omit?: Prisma.WorkoutProgressOmit<ExtArgs> | null
  /**
   * The data used to create many WorkoutProgresses.
   */
  data: Prisma.WorkoutProgressCreateManyInput | Prisma.WorkoutProgressCreateManyInput[]
  skipDuplicates?: boolean
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.WorkoutProgressIncludeCreateManyAndReturn<ExtArgs> | null
}

/**
 * WorkoutProgress update
 */
export type WorkoutProgressUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the WorkoutProgress
   */
  select?: Prisma.WorkoutProgressSelect<ExtArgs> | null
  /**
   * Omit specific fields from the WorkoutProgress
   */
  omit?: Prisma.WorkoutProgressOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.WorkoutProgressInclude<ExtArgs> | null
  /**
   * The data needed to update a WorkoutProgress.
   */
  data: Prisma.XOR<Prisma.WorkoutProgressUpdateInput, Prisma.WorkoutProgressUncheckedUpdateInput>
  /**
   * Choose, which WorkoutProgress to update.
   */
  where: Prisma.WorkoutProgressWhereUniqueInput
}

/**
 * WorkoutProgress updateMany
 */
export type WorkoutProgressUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update WorkoutProgresses.
   */
  data: Prisma.XOR<Prisma.WorkoutProgressUpdateManyMutationInput, Prisma.WorkoutProgressUncheckedUpdateManyInput>
  /**
   * Filter which WorkoutProgresses to update
   */
  where?: Prisma.WorkoutProgressWhereInput
  /**
   * Limit how many WorkoutProgresses to update.
   */
  limit?: number
}

/**
 * WorkoutProgress updateManyAndReturn
 */
export type WorkoutProgressUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the WorkoutProgress
   */
  select?: Prisma.WorkoutProgressSelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the WorkoutProgress
   */
  omit?: Prisma.WorkoutProgressOmit<ExtArgs> | null
  /**
   * The data used to update WorkoutProgresses.
   */
  data: Prisma.XOR<Prisma.WorkoutProgressUpdateManyMutationInput, Prisma.WorkoutProgressUncheckedUpdateManyInput>
  /**
   * Filter which WorkoutProgresses to update
   */
  where?: Prisma.WorkoutProgressWhereInput
  /**
   * Limit how many WorkoutProgresses to update.
   */
  limit?: number
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.WorkoutProgressIncludeUpdateManyAndReturn<ExtArgs> | null
}

/**
 * WorkoutProgress upsert
 */
export type WorkoutProgressUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the WorkoutProgress
   */
  select?: Prisma.WorkoutProgressSelect<ExtArgs> | null
  /**
   * Omit specific fields from the WorkoutProgress
   */
  omit?: Prisma.WorkoutProgressOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.WorkoutProgressInclude<ExtArgs> | null
  /**
   * The filter to search for the WorkoutProgress to update in case it exists.
   */
  where: Prisma.WorkoutProgressWhereUniqueInput
  /**
   * In case the WorkoutProgress found by the `where` argument doesn't exist, create a new WorkoutProgress with this data.
   */
  create: Prisma.XOR<Prisma.WorkoutProgressCreateInput, Prisma.WorkoutProgressUncheckedCreateInput>
  /**
   * In case the WorkoutProgress was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.WorkoutProgressUpdateInput, Prisma.WorkoutProgressUncheckedUpdateInput>
}

/**
 * WorkoutProgress delete
 */
export type WorkoutProgressDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the WorkoutProgress
   */
  select?: Prisma.WorkoutProgressSelect<ExtArgs> | null
  /**
   * Omit specific fields from the WorkoutProgress
   */
  omit?: Prisma.WorkoutProgressOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.WorkoutProgressInclude<ExtArgs> | null
  /**
   * Filter which WorkoutProgress to delete.
   */
  where: Prisma.WorkoutProgressWhereUniqueInput
}

/**
 * WorkoutProgress deleteMany
 */
export type WorkoutProgressDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which WorkoutProgresses to delete
   */
  where?: Prisma.WorkoutProgressWhereInput
  /**
   * Limit how many WorkoutProgresses to delete.
   */
  limit?: number
}

/**
 * WorkoutProgress without action
 */
export type WorkoutProgressDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the WorkoutProgress
   */
  select?: Prisma.WorkoutProgressSelect<ExtArgs> | null
  /**
   * Omit specific fields from the WorkoutProgress
   */
  omit?: Prisma.WorkoutProgressOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.WorkoutProgressInclude<ExtArgs> | null
}
